# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='Бележки',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='Площ на апартамента',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='Дата на встъпване в длъжност',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='Дата на напускане на длъжността',
            field=models.DateField(blank=True, null=True),
        ),
    ]
