# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171028_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='Бележки',
        ),
        migrations.RemoveField(
            model_name='appartment',
            name='Етаж',
        ),
        migrations.RemoveField(
            model_name='appartment',
            name='Номер на апартамента',
        ),
        migrations.RemoveField(
            model_name='appartment',
            name='Площ на апартамента',
        ),
        migrations.RemoveField(
            model_name='appartmenthabitants',
            name='Брой живущи',
        ),
        migrations.RemoveField(
            model_name='appartmenthabitants',
            name='Месец',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Апартамент',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='За месец',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Сума',
        ),
        migrations.RemoveField(
            model_name='entrance',
            name='Брой апартаменти',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='Дата на встъпване в длъжност',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='Дата на напускане на длъжността',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='Име',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='Фамилия',
        ),
        migrations.AddField(
            model_name='appartment',
            name='area',
            field=models.FloatField(blank=True, help_text='Площ на апартамента', null=True),
        ),
        migrations.AddField(
            model_name='appartment',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, help_text='Етаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartment',
            name='notes',
            field=models.TextField(blank=True, help_text='Бележки', null=True),
        ),
        migrations.AddField(
            model_name='appartment',
            name='number',
            field=models.CharField(default=1, help_text='Номер на апартамента', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartmenthabitants',
            name='month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Месец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartmenthabitants',
            name='number',
            field=models.IntegerField(default=1, help_text='Брой живущи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=1, help_text='Сума'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='appartment',
            field=models.ForeignKey(default=1, help_text='Апартамент', on_delete=django.db.models.deletion.CASCADE, to='core.Appartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='for_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='За месец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrance',
            name='number_appartments',
            field=models.IntegerField(default=1, help_text='Брой апартаменти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managers',
            name='first_name',
            field=models.CharField(default=1, help_text='Име', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managers',
            name='last_name',
            field=models.CharField(default=1, help_text='Фамилия', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managers',
            name='office_end_date',
            field=models.DateField(blank=True, help_text='Дата на напускане на длъжността', null=True),
        ),
        migrations.AddField(
            model_name='managers',
            name='office_start_date',
            field=models.DateField(blank=True, help_text='Дата на встъпване в длъжност', null=True),
        ),
    ]
