# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171028_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartmenthabitants',
            name='appartment',
            field=models.ForeignKey(default=1, help_text='Апартамент', on_delete=django.db.models.deletion.CASCADE, to='core.Appartment'),
            preserve_default=False,
        ),
    ]
