# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appartmenthabitants_appartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartmenthabitants',
            name='month',
            field=models.DateField(help_text='Месец/Година'),
        ),
    ]
