# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171028_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='for_month',
            field=models.DateField(help_text='Месец/Година'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='for_month',
            field=models.DateField(help_text='Месец/Година'),
        ),
    ]
