# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171028_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartmentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Сума')),
                ('for_month', models.DateField(help_text='Месец/Година')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='appartment',
        ),
        migrations.AddField(
            model_name='appartment',
            name='common_part_percent',
            field=models.FloatField(default=1, help_text='Процент идеални части'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.AddField(
            model_name='appartmentbill',
            name='appartment',
            field=models.ForeignKey(help_text='Апартамент', on_delete=django.db.models.deletion.CASCADE, to='core.Appartment'),
        ),
    ]
