# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171029_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='pay_for_elevator_electricity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appartment',
            name='pay_for_elevator_maintenance',
            field=models.BooleanField(default=True),
        ),
    ]
