# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171029_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='common_part_percent_rounded',
            field=models.FloatField(default=1, help_text='Процент идеални части (закръглен)'),
            preserve_default=False,
        ),
    ]
