# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appartment_common_part_percent_rounded'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBillAppartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Сума')),
                ('for_month', models.DateField(help_text='Месец/Година')),
                ('appartment', models.ForeignKey(help_text='Апартамент', on_delete=django.db.models.deletion.CASCADE, to='core.Appartment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RecurringBillType')),
            ],
        ),
    ]
