# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_recurringbillappartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbillappartment',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Дата на плащане', null=True),
        ),
    ]
